config/routes.rb
Rails.application.routes.draw do
  root "howls#top"
  get "/howls", to: "howls#index"

  resources :howls do
    post :confirm, on: :collection
  end

  get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :favorites, only: [:create, :destroy]

  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"


  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :content, length: { in: 1..140 }

  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :howl
end

app/models/howl.rb
class Howl < ApplicationRecord
    validates :content, length: { in: 1..140 }

    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :favorites, dependent: :destroy
  has_many :howls
  has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :your_contact, only: [:index, :new, :edit, :show]
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.name.empty?
      @contact.name = current_user.name
    end

    if @contact.email.empty?
      @contact.email = current_user.email
    end

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'お問い合わせを送信しました' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    @contact.user_id = current_user.id
    respond_to do |format|
      if @contact.update(contact_params)
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'お問い合わせを再送信しました' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end

    def your_contact
      unless logged_in?
        redirect_to new_session_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(howl_id: params[:howl_id])
    redirect_to favorite.howl, notice: "#{favorite.howl.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to favorite.howl, notice: "#{favorite.howl.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/howls_controller.rb
class HowlsController < ApplicationController
  before_action :set_howl, only: [:show, :edit, :update, :destroy]
  before_action :your_page, only: [:show, :destroy]
  before_action :edit_restriction, only: [:edit]
  def index
    @howls = Howl.all
  end

  def new
    if params[:back]
      get_howl
    else
      @howl = Howl.new
      @howl.user_id = current_user.id
    end
  end

  def create
    @howl = Howl.new(howl_params)
    @howl.user_id = current_user.id
    # if @howl.save
    #   redirect_to howls_path, notice: "作成しました"
    # else
    #   render "new"
    # end
      respond_to do |format|
        if @howl.save
          HowlMailer.howl_mail(@howl).deliver
          format.html { redirect_to @howl, notice: '作成しました' }
          format.json { render :show, status: :created, location: @howl }
        else
          format.html { render :new }
          format.json { render json: @howl.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
    @favorite = current_user.favorites.find_by(howl_id: @howl.id)
  end

  def edit
  end


  def update
    if @howl.update(howl_params)
      redirect_to howls_path, notice: "編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @howl.destroy
    redirect_to howls_path, notice: "削除しました"
  end

  def confirm
    get_howl
    @howl.user_id = current_user.id
    render :new if @howl.invalid?
  end

  private
    def howl_params
      params.require(:howl).permit(:content)
    end

    def set_howl
      @howl = Howl.find(params[:id])
    end

    def get_howl
      @howl = Howl.new(howl_params)
    end

    def your_page
      unless logged_in?
        redirect_to new_session_path
      end
    end

    def edit_restriction
      unless logged_in? && @howl.user_id == current_user.id
        redirect_to user_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインできません"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_howls = @user.favorites.all
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/howls_helper.rb
module HowlsHelper
    def choose_new_or_edit
        if action_name == "new" || action_name == "confirm"
            confirm_howls_path
        elsif action_name == "edit"
            howl_path
        end
    end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<div class="editting_form container">
      <%= form_with(model: contact, local: true) do |form| %>
        <% if contact.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% contact.errors.full_messages.each do |message| %>
                <li><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="edit_form row">
            <div class="howl_new col-sm-6 col-md-4">
                <%= form.label :内容を編集してください, class: "action_order" %>
                <%= form.text_area :content, id: :contact_content, class: "field_size" %>
            </div>
        </div>

        <div class="explanation">
          <p>登録完了後、ご指定のメールアドレスに確認メールが届きます。<br>*もし指定がなければ下記のメールアドレスにメールが届きます。</p>
        </div>

        <div class="input_column">
          <table>
            <tr>
              <td><%= form.label :name %></td>
              <td><%= form.text_field :name, id: :contact_name, :placeholder => current_user.name %></td>
            </tr>

            <tr>
              <td><%= form.label :email %></td>
              <td><%= form.text_field :email, id: :contact_email, :placeholder => current_user.email %></td>
            </tr>
          </table>
        </div>

        <div class="actions">
          <%= form.submit "登録する", class: "confirm_function" %>
        </div>
    <% end %>
</div>

app/views/contacts/edit.html.erb
<div class="editting_form container">
  <h1><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>お問い合わせ内容の編集</h1>

  <div class="editting_column">
      <div class="action_order">編集された内容は再度お問い合わせとして送信されます</div>
  </div>

  <%= render 'form', contact: @contact %>

  <div class="move_pages">
      <p><%= link_to "お問い合わせ履歴", contacts_path, class: "move_pages_function" %></p>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="index_form container">
  <h1>お問い合わせ履歴</h1>
  <p id="notice"><%= notice %></p>

  <div class="posted_sum row table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-xs-2">お名前</th>
          <th class="col-xs-2">登録メールアドレス</th>
          <th class="col-xs-2">お問い合わせ内容</th>
          <th class="col-xs-2"></th>
          <th class="col-xs-2"></th>
          <th class="col-xs-2"></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
         <% if contact.user_id == current_user.id %>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.email %></td>
              <td><%= contact.content %></td>
              <td><%= link_to '詳細', contact, class: "sum_function" %></td>
              <td><%= link_to '編集', edit_contact_path(contact), class: "sum_function" %></td>
              <td><%= link_to '削除', contact, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "sum_function" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>




  <div class="move_pages">
    <p><%= link_to '新しいお問い合わせをする', new_contact_path, class: "move_pages_function" %></p>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="editting_form container">
  <h1><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>お問い合わせ内容の作成</h1>
  <%= render 'form', contact: @contact %>

  <div class="move_pages">
      <p><%= link_to "お問い合わせ履歴", contacts_path, class: "move_pages_function" %></p>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="editting_form container">
      <h1><span class="glyphicon glyphicon-send" aria-hidden="true"></span>ありがとうございました</h1>
      <p id="notice"><%= notice %></p>

      <div class="editting_column">
  <p>お名前：<%= @contact.name %></p>
  <p>メールアドレス：<%= @contact.email %></p>
  <p>お問い合わせ内容：<%= @contact.content %></p>
</div>
  <div class="move_pages">
      <p><%= link_to "再編集する", edit_contact_path(@contact), class: "move_pages_function" %></p>
      <p><%= link_to "お問い合わせ履歴", contacts_path, class: "move_pages_function" %></p>
  </div>
</div>

app/views/howls/confirm.html.erb
<div class="editting_form container">
    <h1><span class="glyphicon glyphicon-send" aria-hidden="true"></span>以下で登録</h1>

    <div class="editting_column">
    <%= form_with(model: @howl, local: true, url: howls_path) do |form| %>
        <%= form.hidden_field :content %>
        
        <%= form.label :内容を確認してください, class: "action_order" %>
        <div class="content_check_msg"><%= @howl.content %></div>
        <%= form.submit "登録", class: "confirm_function" %>
    <% end %>
    </div>
    
    <%= form_with(model: @howl, local: true, url: new_howl_path, method: "get") do |form| %>
        <%= form.hidden_field :content %>
        <%= form.submit "編集に戻る", name: "back", class: "move_pages_function" %>
    <% end %>
</div>

app/views/howls/edit.html.erb
<div class="editting_form">
    <h1><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>投稿編集</h1>
    <%= render "form" %>
</div>

app/views/howls/index.html.erb
<div class="index_form container">
    <h1>投稿一覧</h1>
    <p><%= notice %></p>
    <div class="posted_sum row">
        <% @howls.each do |howl| %>
            <div class="posted_column col-sm-6 col-lg-4">
                <div class="posted_column_content row">
                    <p class="col-xs-2"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span></p>
                    <p class="col-xs-7"><%= howl.user.name %>さんの投稿</p>
                    <p class="col-xs-3"><%= howl.content %></p>
                </div>
                <div class="posted_column_buttons row">
                    <p><%= link_to "詳細", howl_path(howl.id), class: "sum_function col-xs-4", style: "margin-top: 10px" %></p>
                    <% if howl.user == current_user %>
                      <p><%= link_to "編集", edit_howl_path(howl.id), class: "sum_function col-xs-4" %></p>
                      <p><%= link_to "削除", howl_path(howl.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "sum_function col-xs-4" %></p>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="move_pages">
          <% if logged_in? %>
            <p><%= link_to "新しい投稿をする", new_howl_path, class: "move_pages_function" %></p>
            <p><%= link_to "ログアウトする", session_path(current_user.id), method: :delete, data: {confirm: "本当にログアウトしますか？"}, class: "confirm_function" %></p>
          <% else %>
            <p><%= link_to "ログインする", new_session_path, class: "confirm_function" %></p>
          <% end %>
        <p><%= link_to "Topに戻る", root_path, class: "move_pages_function" %></p>
    </div>
</div>

app/views/howls/new.html.erb
<div class="editting_form">
    <h1><span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>新規投稿</h1>
    <%= render "form" %>
</div>

app/views/howls/show.html.erb
<div class="editting_form container">
    <h1><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>詳細確認</h1>

    <div class="editting_column">
        <div class="action_order">OWLメッセージがたくさん来ると良いですね</div>
        <div class="content_check_msg"><%= @howl.content %></div>
    </div>

    <div class="move_pages">
        <p><%= link_to "一覧に戻る", howls_path, class: "move_pages_function" %></p>
        <p>
          <% unless @howl.user == current_user %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(howl_id: @howl.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        </p>
    </div>



</div>

app/views/howls/top.html.erb
<div class="container-fruid">
    <div class="parallax">
        <div class="parallax_title">
            <h4>HOWL(ハウル)の意味：</h4>
            <p>天を仰ぎながら長く鳴き声を上げる独特の鳴き方</p>
            <p>イヌ科の動物、特に狼に強く見られる習性で、遠方にいる仲間とのコミュニケーションや群れの連携における何かしら合図、仲間とはぐれたときの救難信号などの意図を伝えるためにおこなう</p>
        </div>
    </div>

    <div class="wrapper row">
        <div class="wrapper_left col-md-6">
            <table>
                <tr>
                    <td><%= image_tag "logo1.png", :width => '60' %></td>
                    <td>
                        <h4>HOWLERs COMMUNITY</h4>
                        <p>溜まったストレスは書いて消化しよう</p>
                    </td>
                </tr>
                <tr>
                    <td><%= image_tag "logo2.png", :width => '70' %></td>
                    <td>
                        <h4>MATEs BUTTON</h4>
                        <p>共感できる、賛同出来る、仲間の声に応えよう</p>
                    </td>
                </tr>
                <tr>
                    <td><%= image_tag "logo3.png", :width => '80' %></td>
                    <td>
                        <h4>OWL MESSAGE</h4>
                        <p>知恵の鳥、フクロウメッセージでアドバイスしあおう</p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="wrapper_right col-md-6">
            <%= image_tag "shadow_logo3.png", :height => '300', :class => "shadow_logo3" %>

            <div class="wrapper_right_title">
                <h2>悩み、ストレスは書きだそう。助け合おう。</h2>
                <h4>HOWLをはじめる</h4>
                <ul>
                    <li>
                        <button type="button" class="btn btn-default btn-lg">
                          <% if logged_in? %>
                            <%= link_to "投稿一覧", howls_path %>
                          <% else %>
                            <%= link_to "アカウント作成", new_user_path %>
                          <% end %>
                        </button>
                    </li>

                    <li>
                        <button type="button" class="btn btn-default btn-lg">
                          <% if logged_in? %>
                            <%= link_to "ログアウト", session_path(current_user.id), method: :delete, data: {confirm: "本当にログアウトしますか？"} %>
                          <% else %>
                            <%= link_to "ログイン", new_session_path %>
                          <% end %>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="summary">
        <h4>HOWL is about</h4>
        <h2>SHARING NEGATIVES & HELP EACH OTHER</h2>
        <p>賛同出来る仲間が遠吠えで応えてくれる。OWLメッセージでアドバイスがもらえる。</p>
        <p>3つのポイント</p>
    </div>

    <div class="features row">
        <div class="feature col-md-4">
            <div class="feature_column">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '60' %></td>
                        <td><h3>HOWLERs COMMUNITY</h3></td>
                    </tr>
                </table>
            <p class="feature_content">最近ストレスちゃんと解消できてる？<br>ネガティブな感情は溜めないでHOWLに書き出して解消していこう。</p>
            </div>
        </div>

        <div class="feature col-md-4">
            <div class="feature_column">
                <table>
                    <tr>
                        <td><%= image_tag "logo5.png", :width => '90' %></td>
                        <td><h3>MATEs BUTTON</h3></td>
                    </tr>
                </table>
                <p class="feature_content">あなたは一人じゃない。<br>あなたの悩みに共感する世界中の仲間がMATEsボタンで応えてくれる。</p>
            </div>
        </div>

        <div class="feature col-md-4">
            <div class="feature_column">
                <table>
                    <tr>
                        <td><%= image_tag "logo6.png", :width => '110' %></td>
                        <td><h3>OWL MESSAGE</h3></td>
                    </tr>
                </table>
                <p class="feature_content">あなたの経験が仲間を救う。<br>誰かの悩みを見たら励ましの言葉、アドバイスや解決法をOWLメッセージで残そう。</p>
            </div>
        </div>
    </div><!-- features row -->

    <div class="other_howls">
        <div class="other_howls_title">
            <h4>HOWL is about</h4>
            <h2>GET ADVICE & GIVE ADVICE</h2>
            <div class="move_pages">
              <p><%= link_to "みんなのHowlを見てみよう", howls_path, class: "move_pages_function" %></p>
            </div>
        </div>

        <div class="other_howls_content row">
            <div class="other_howls_content_one col-sm-6">
            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Millie Bobby Brown</p></td>
                    </tr>
                </table>
                <p>Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>

            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Justin Trudeau</p></td>
                    </tr>
                </table>
                <p>On #WorldChildrensDay, let’s make sure every child gets the love, safety, and support they need to pursue their dreams. https://twitter.com/UN/status/9326. We’re raising our voices to help save children’s lives, fight for their rights and help them reach their full potential. Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>

            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Malala</p></td>
                    </tr>
                </table>
                <p>To every child - I dream of a world where you can laugh, dance, sing, learn, live in peace and be happy.#WorldChildrensDay</p>
            </div>

            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Sophie Wisbrun</p></td>
                    </tr>
                </table>
                <p>#ForEveryChild a happy healthy sustainable future today and forever! #WorldChildrensDay @UNICEF. A day for children, by children. We’re raising our voices to help save children’s lives, fight for their rights and help them reach their full potential. Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>
        </div>
            <div class="other_howls_content_two col-sm-6">
            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Millie Bobby Brown</p></td>
                    </tr>
                </table>
                <p>A day for children, by children. We’re raising our voices to help save children’s lives, fight for their rights and help them reach their full potential. Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>

            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Millie Bobby Brown</p></td>
                    </tr>
                </table>
                <p>Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>

            <div class="other_howl">
                <table>
                    <tr>
                        <td><%= image_tag "logo4.png", :width => '40' %></td>
                        <td><p>Millie Bobby Brown</p></td>
                    </tr>
                </table>
                <p>I’m here overseas kicking off #WorldChildrensDay! A day for children, by children. We’re raising our voices to help save children’s lives, fight for their rights and help them reach their full potential. Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensdayI’m here overseas kicking off #WorldChildrensDay! A day for children, by children. We’re raising our voices to help save children’s lives, fight for their rights and help them reach their full potential. Click on the link to learn more about @UNICEF http://uni.cf/worldchildrensday</p>
            </div>
        </div>
        </div>
    </div><!-- other_howls rows -->
</div><!-- container-fruid -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppHowl</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to "HOWL", { :controller => "howls", :action => "top" }, { :class => "navbar-brand" }  %>
              </div><!-- navbar-header -->

              <div id="gnavi" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li>
                    <% if logged_in? %>
                      <%= link_to "ログアウト", session_path(current_user.id), method: :delete, data: {confirm: "本当にログアウトしますか？"} %>
                    <% else %>
                      <%= link_to "ログイン", new_session_path %>
                    <% end %>
                  </li>

                  <li>
                    <% if logged_in? %>
                      <%= link_to "マイページ", user_path(current_user.id) %>
                    <% end %>
                  </li>

                  <li><%= link_to "投稿一覧を見る", howls_path %></li>

                  <li>
                    <% if logged_in? %>
                      <%= link_to "お問い合わせ", new_contact_path(current_user.id) %>
                    <% end %>
                  </li>
                </ul>
              </div><!-- navbar-collapse -->
            </div><!-- container-fluid -->
          </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="footer_title">
          <% if logged_in? %>
            <p><%= @current_user.name %>さんとしてログイン中</p>
          <% end %>
        <p>© Copyright DIVE INTO CODE Corp. 2018</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="editting_form container">
  <% if logged_in? %>
    <h1>こんにちは、<%= current_user.name %>さん</h1>
    <div class="action_order">登録メールアドレスは<%= current_user.email %>です</div>
    <div class="move_pages">
        <p><%= link_to "投稿一覧を見る", howls_path, class: "move_pages_function" %></p>
        <p><%= link_to "新規投稿をする", new_howl_path, class: "move_pages_function" %></p>
        <p><%= link_to "Topに戻る", root_path, class: "move_pages_function" %></p>
        <p><%= link_to "ログアウト", session_path(current_user.id), method: :delete, data: {confirm: "本当にログアウトしますか？"}, class: "confirm_function" %></p>
    </div>

    <div class="favorites_list row">
      <div class="favorites_list_title">お気に入り投稿一覧</div>
      <% @favorites_howls.all.each do |favorite| %>
        <div class="posted_column col-sm-6">
            <div class="posted_column_content row">
                <p class="col-xs-3"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span></p>
                <p class="col-xs-5"><%= favorite.howl.user.name %>さんの投稿</p>
                <p class="col-xs-2"><%= favorite.howl.content %></p>
                <p><%= link_to "詳細", howl_path(favorite.howl.id), class: "sum_function col-xs-2" %></p>
            </div>
        </div>
      <% end %>
    </div>

    <div class="move_pages">
        <p><%= link_to "お問い合わせ履歴", contacts_path, class: "move_pages_function" %></p>
    </div>

  <% else %>
    <h1>登録完了</h1>
    <div class="action_order">ご登録ありがとうございました</div>
    <div class="move_pages">
        <p><%= link_to "早速Howlを始める", new_session_path, class: "confirm_function" %></p>
        <p><%= link_to "Topに戻る", root_path, class: "move_pages_function" %></p>
    </div>
  <% end %>
</div>